-- Populate default EOL / SHIPMENT / TEST templates (migration 0002).
-- Source: live DB active checklist_template_items (exact text, incl. trailing newlines).
-- Idempotent: ON CONFLICT (template_id, item_no) DO UPDATE.
-- Excludes inactive and test-only items (see seed README / task report).
WITH template_items (
    template_name,
    item_no,
    item_text,
    eol_phase,
    section_key,
    section_sort
) AS (
    VALUES

        -- EOL: 15 active items
        ('Default EoL Template (16 items, Branch + Depot)', 1::SMALLINT, 'Software Update', 'BRANCH'::eol_item_phase_enum, NULL::varchar, NULL::smallint),
        ('Default EoL Template (16 items, Branch + Depot)', 2, 'Araç Motoru', 'BRANCH', NULL, NULL),
        ('Default EoL Template (16 items, Branch + Depot)', 3, 'Batarya', 'BRANCH', NULL, NULL),
        ('Default EoL Template (16 items, Branch + Depot)', 4, 'Süspansiyon Testi', 'BRANCH', NULL, NULL),
        ('Default EoL Template (16 items, Branch + Depot)', 5, 'Fonksiyonel Komponet Kontrolü', 'BRANCH', NULL, NULL),
        ('Default EoL Template (16 items, Branch + Depot)', 6, 'Fren/El Testi', 'BRANCH', NULL, NULL),
        ('Default EoL Template (16 items, Branch + Depot)', 7, 'Far Ayarı', 'BRANCH', NULL, NULL),
        ('Default EoL Template (16 items, Branch + Depot)', 8, 'Rot Balans', 'BRANCH', NULL, NULL),
        ('Default EoL Template (16 items, Branch + Depot)', 9, 'Sürüş', 'BRANCH', NULL, NULL),
        ('Default EoL Template (16 items, Branch + Depot)', 10, 'Görsel Kontrol', 'BRANCH', NULL, NULL),
        ('Default EoL Template (16 items, Branch + Depot)', 11, 'Depo Sürüş', 'DEPOT', NULL, NULL),
        ('Default EoL Template (16 items, Branch + Depot)', 12, 'Bumpy Road', 'DEPOT', NULL, NULL),
        ('Default EoL Template (16 items, Branch + Depot)', 13, 'Yağmur Testi', 'DEPOT', NULL, NULL),
        ('Default EoL Template (16 items, Branch + Depot)', 14, 'EE Check', 'DEPOT', NULL, NULL),
        ('Default EoL Template (16 items, Branch + Depot)', 15, 'Görsel Kontrol 2', 'DEPOT', NULL, NULL),

        -- SHIPMENT: 46 active items
        ('Default Customer Vehicle Checklist (43 items)', 1, E'Rear Bota Ses İzolasyonu Montaj\n', NULL, 'identity', 10),
        ('Default Customer Vehicle Checklist (43 items)', 2, 'Front Dash Ses İzolasyonu Montaj', NULL, 'identity', 10),
        ('Default Customer Vehicle Checklist (43 items)', 3, 'Sol Air Flap Montaj', NULL, 'identity', 10),
        ('Default Customer Vehicle Checklist (43 items)', 4, 'Sağ Air Flap Montaj', NULL, 'identity', 10),
        ('Default Customer Vehicle Checklist (43 items)', 5, 'C_Pillar Inner Sol Kesim', NULL, 'identity', 10),
        ('Default Customer Vehicle Checklist (43 items)', 6, E'C_Pillar Inner Sağ Kesim\n', NULL, 'identity', 10),
        ('Default Customer Vehicle Checklist (43 items)', 7, 'Polen Filtresi Montaj', NULL, 'exterior', 20),
        ('Default Customer Vehicle Checklist (43 items)', 8, 'C_Pillar Inner Support M5 Delik Sağ', NULL, 'exterior', 20),
        ('Default Customer Vehicle Checklist (43 items)', 9, 'C_Pillar Inner Support M5 Delik Sol', NULL, 'exterior', 20),
        ('Default Customer Vehicle Checklist (43 items)', 10, 'C_Pillar Yeni Clips Değişmesi', NULL, 'exterior', 20),
        ('Default Customer Vehicle Checklist (43 items)', 11, 'C_Pillar Stop tırnaklarının kesilmesi', NULL, 'exterior', 20),
        ('Default Customer Vehicle Checklist (43 items)', 12, 'Headliner Yeni Clips Değişmesi', NULL, 'exterior', 20),
        ('Default Customer Vehicle Checklist (43 items)', 13, 'Knuckle 2,5 mm Slot Açılması ve 1 derece Ayarı', NULL, 'exterior', 20),
        ('Default Customer Vehicle Checklist (43 items)', 14, 'CCB Korna Şasi Almaması Dolaylı Harness', NULL, 'exterior', 20),
        ('Default Customer Vehicle Checklist (43 items)', 15, 'Kapı direk plastik parça sıvı conta uygulaması', NULL, 'exterior', 20),
        ('Default Customer Vehicle Checklist (43 items)', 16, 'Ayarlı dış aynaların takılması', NULL, 'exterior', 20),
        ('Default Customer Vehicle Checklist (43 items)', 17, 'Logo montajı', NULL, 'locks', 30),
        ('Default Customer Vehicle Checklist (43 items)', 18, E'Anahtarlık logosu değişimi\n', NULL, 'locks', 30),
        ('Default Customer Vehicle Checklist (43 items)', 19, 'Direksiyon Logo Değişimi', NULL, 'locks', 30),
        ('Default Customer Vehicle Checklist (43 items)', 20, 'Jant Logo Değişimi', NULL, 'locks', 30),
        ('Default Customer Vehicle Checklist (43 items)', 21, E'HVAC kapama parçası takılması\n', NULL, 'lighting', 40),
        ('Default Customer Vehicle Checklist (43 items)', 22, E'Trunk Diveder parça takılması\n', NULL, 'lighting', 40),
        ('Default Customer Vehicle Checklist (43 items)', 23, E'Araç tanıtım etiketi perçinlenmesi\n', NULL, 'lighting', 40),
        ('Default Customer Vehicle Checklist (43 items)', 24, 'VIN markalaması', NULL, 'lighting', 40),
        ('Default Customer Vehicle Checklist (43 items)', 25, 'Kapı ayar kauçuklarının takılması', NULL, 'lighting', 40),
        ('Default Customer Vehicle Checklist (43 items)', 26, 'Kaput ayar kauçuklarının takılması', NULL, 'lighting', 40),
        ('Default Customer Vehicle Checklist (43 items)', 27, 'Chogori IP68 kablonun araca konulması', NULL, 'lighting', 40),
        ('Default Customer Vehicle Checklist (43 items)', 28, 'Anti Scratch film tampona kaplanması', NULL, 'interior', 50),
        ('Default Customer Vehicle Checklist (43 items)', 29, 'Anti Fog Film cama kaplanması', NULL, 'interior', 50),
        ('Default Customer Vehicle Checklist (43 items)', 30, 'Kaput altı sızdırmazlık contasının kullanılması', NULL, 'interior', 50),
        ('Default Customer Vehicle Checklist (43 items)', 31, 'P silinmiş combination switch kullanılması', NULL, 'interior', 50),
        ('Default Customer Vehicle Checklist (43 items)', 32, 'Kelebek camı düşmemesi için sünger konulması', NULL, 'interior', 50),
        ('Default Customer Vehicle Checklist (43 items)', 33, 'El Fren Ayarı yapılması ve arka disklere denk gelen noktada doğru konumlanması', NULL, 'interior', 50),
        ('Default Customer Vehicle Checklist (43 items)', 34, 'IP yanı kapı harness ve kapı clips bölgesinde sızdırmazlıkların tam olması', NULL, 'interior', 50),
        ('Default Customer Vehicle Checklist (43 items)', 35, 'Arka kapı sağ alt sızdırmazlık şeridi çekilmesi', NULL, 'interior', 50),
        ('Default Customer Vehicle Checklist (43 items)', 36, 'Arka kapı sol alt sızdırmazlık şeridi çekilmesi', NULL, 'charge', 60),
        ('Default Customer Vehicle Checklist (43 items)', 37, 'Arka kapı sağ üst sızdırmazlık şeridi çekilmesi', NULL, 'charge', 60),
        ('Default Customer Vehicle Checklist (43 items)', 38, 'Arka kapı sol üst sızdırmazlık şeridi çekilmesi', NULL, 'charge', 60),
        ('Default Customer Vehicle Checklist (43 items)', 39, 'Arka davlumbaz sol fren borusu girişim bölgesi kesimi', NULL, 'charge', 60),
        ('Default Customer Vehicle Checklist (43 items)', 40, 'Arka davlumbaz sağ fren borusu girişim bölgesi kesimi', NULL, 'charge', 60),
        ('Default Customer Vehicle Checklist (43 items)', 41, E'Direksiyon yumusatma ayari\n', NULL, 'charge', 60),
        ('Default Customer Vehicle Checklist (43 items)', 42, E'Stop delik genisletme yapildi mi\n', NULL, 'charge', 60),
        ('Default Customer Vehicle Checklist (43 items)', 43, 'Kaput ayar pulu atıldı mı', NULL, 'charge', 60),
        ('Default Customer Vehicle Checklist (43 items)', 44, 'Direksiyon kolonu dip lastiği yerine tam olarak oturmuş mu', NULL, NULL, NULL),
        ('Default Customer Vehicle Checklist (43 items)', 45, 'Kaput civatalarinin piano black rötuş kalemi ile boyanmasi', NULL, NULL, NULL),
        ('Default Customer Vehicle Checklist (43 items)', 46, 'Bagaj kapagi su sizdirma problemi parca entegrasyonu', NULL, NULL, NULL),

        -- TEST: 43 active items
        ('Default Test Checklist (45 items)', 1, 'N''de aracı ittir — Anormal direnç var mı?', NULL, 'brakes', 10),
        ('Default Test Checklist (45 items)', 2, 'D''de gaz ver — Araç normal hızlanıyor mu? Sıkma hissi veya anormal ses var mı?', NULL, 'brakes', 10),
        ('Default Test Checklist (45 items)', 3, 'R''de gaz ver — Geri viteste normal hızlanıyor mu? Sıkma hissi veya anormal ses var mı?', NULL, 'brakes', 10),
        ('Default Test Checklist (45 items)', 4, 'Dış aydınlatma — Kısa, uzun, selektör, park, sis, sol/sağ sinyal, dörtlü, stop, geri vites lambası.', NULL, 'brakes', 10),
        ('Default Test Checklist (45 items)', 5, 'Korna — Ses seviyesi ve çalışması normal mi?', NULL, 'steering', 20),
        ('Default Test Checklist (45 items)', 6, 'Camlar — Tüm camlar açılıp kapanıyor mu? Takılma, yavaşlık veya ses var mı?', NULL, 'steering', 20),
        ('Default Test Checklist (45 items)', 7, 'Merkezi kilit & kapılar — İçeriden ve anahtarla dışarıdan kilitle-aç. Her kapıda doğru çalışıyor mu?', NULL, 'steering', 20),
        ('Default Test Checklist (45 items)', 8, 'Aynalar & iç donanım — Aynalar, IP kapakları, emniyet kemeri kapakları, düğmeler ve trim parçaları normal mi?', NULL, 'lights', 30),
        ('Default Test Checklist (45 items)', 9, 'Emniyet kemerleri — Tokalar çalışıyor mu? Kemer düzgün sarıyor mu? Uyarı sesi/ikonu doğru mu?', NULL, 'lights', 30),
        ('Default Test Checklist (45 items)', 10, E'El freni (KRİTİK) — El frenini çek $\\rightarrow$ hafif gaz ver $\\rightarrow$ araç ilerlemeye çalışıyor mu? Kayma varsa video + SOC% + saat.', NULL, 'lights', 30),
        ('Default Test Checklist (45 items)', 11, 'Vites seçimi — P/R/N/D geçişlerinde gecikme, yanlış gösterim veya kararsızlık var mı?', NULL, 'diag', 40),
        ('Default Test Checklist (45 items)', 12, 'Ana ekran / menüler — Tüm menülerde düğmelere tek tek bas. Donma, sıfırlanma veya gecikme var mı?', NULL, 'diag', 40),
        ('Default Test Checklist (45 items)', 13, 'Geri görüş kamerası — R''ye alınca görüntü geliyor mu? Görüntü temiz mi?', NULL, 'hv', 50),
        ('Default Test Checklist (45 items)', 14, 'Klima & havalandırma — Fan 1-2-3, yüze/cama üfleme, iç hava dolaşımı, A/C, ısıtma/soğutma.', NULL, 'hv', 50),
        ('Default Test Checklist (45 items)', 15, 'Odometer — Sürüş öncesi değeri not et. Sürüş sonrası doğru sayıyor mu? Aracı kapatıp açınca kaldığı yerden devam ediyor mu?', NULL, 'hv', 50),
        ('Default Test Checklist (45 items)', 16, E'Düşük hız — 500m, 0 $\\rightarrow$ 30 km/s. Titreme, silkelenme, anormal ses, çekişte kararsızlık var mı? Trim/tavan/torpido/kapı/cam sesi var mı?', NULL, 'hv', 50),
        ('Default Test Checklist (45 items)', 17, E'Fren — 30 $\\rightarrow$ 0 x5 (~300m). Her frenlemede sağa/sola ekstrem çekme var mı? Anormal pedal, ses veya titreşim var mı?', NULL, 'drive', 60),
        ('Default Test Checklist (45 items)', 18, 'Sürekli frenleme — Dur-kalk min. 20x (~600m). Pedal sertleşmesi/boşalması, performans düşüşü veya koku var mı?', NULL, 'drive', 60),
        ('Default Test Checklist (45 items)', 19, E'Fren — 50 $\\rightarrow$ 0 x5 (~400m). Her frenlemede sağa/sola ekstrem çekme var mı? Anormal pedal, ses, titreşim veya koku var mı?', NULL, 'drive', 60),
        ('Default Test Checklist (45 items)', 20, E'Fren — 90 $\\rightarrow$ 0 / 80 $\\rightarrow$ 0 / 70 $\\rightarrow$ 0 (~500m). Her frenlemede sağa/sola ekstrem çekme var mı? Performans düşüşü veya koku var mı?', NULL, 'drive', 60),
        ('Default Test Checklist (45 items)', 21, 'Son hıza ulaşma (~600m) — ECO modda 90 km/s''ye ulaşıyor mu? SPORT modda 90 km/s''ye ulaşıyor mu?', NULL, 'drive', 60),
        ('Default Test Checklist (45 items)', 22, 'Yokuş çıkış + iniş (~400m) — Çıkışta geri kaçırma, çekiş düşmesi var mı? İnişte rejen açık/kapalı davranışı normal mi?', NULL, 'dash', 70),
        ('Default Test Checklist (45 items)', 23, E'Yokuş el freni (KRİTİK) — Yokuşta en az 6 kez kaydır-tut. El freni çek $\\rightarrow$ hafif gaz $\\rightarrow$ kayıyor mu? Kayma varsa video + SOC% + saat.', NULL, 'dash', 70),
        ('Default Test Checklist (45 items)', 24, 'N''de yokuş fren testi (~100m) — Yokuş aşağı N''de fren yap, bırak. Araç kendi kendine hareket ediyor mu?', NULL, 'dash', 70),
        ('Default Test Checklist (45 items)', 25, E'Düşük hız fren genel — 30 $\\rightarrow$ 0 testlerinde tutarlı performans sağlandı mı?', NULL, 'dash', 70),
        ('Default Test Checklist (45 items)', 26, E'Orta hız fren genel — 50 $\\rightarrow$ 0 testlerinde tutarlı performans sağlandı mı?', NULL, 'body', 80),
        ('Default Test Checklist (45 items)', 27, E'Yüksek hız fren genel — 90/80/70 $\\rightarrow$ 0 testlerinde tutarlı performans sağlandı mı?', NULL, 'body', 80),
        ('Default Test Checklist (45 items)', 28, 'FRENLERDE SIKMA VAR MI? (KRİTİK) — Anormal direnç, tek taraflı ısınma, koku veya sürtünme hissi var mı? Varsa video + foto + saat.', NULL, 'body', 80),
        ('Default Test Checklist (45 items)', 29, 'Nihai Fren Onayı — Tüm fren testleri tamamlandı, anormal bulgu yok mu?', NULL, 'body', 80),
        ('Default Test Checklist (45 items)', 30, 'Rot ayarı — Düz/eğimsiz yolda direksiyonu bırak. Araç sola veya sağa çekiyor mu?', NULL, 'adas', 90),
        ('Default Test Checklist (45 items)', 31, 'Direksiyon merkezi — Düz gidişte direksiyon tam ortada mı? Belirgin sapma varsa foto + not al.', NULL, 'adas', 90),
        ('Default Test Checklist (45 items)', 32, 'Yüksek hızda kararlılık — 70–90 km/s''de araç düz gidiyor mu? Çekme veya titreşim var mı?', NULL, 'adas', 90),
        ('Default Test Checklist (45 items)', 33, 'Sol ön disk — Elini yaklaştır (dokunma). Diğer disklere kıyasla belirgin sıcak mı? Sıcaksa sıkma şüphesi; foto + not al.', NULL, 'adas', 90),
        ('Default Test Checklist (45 items)', 34, 'Sağ ön disk — Aynı kontrol. Belirgin şekilde sıcak mı?', NULL, 'adas', 90),
        ('Default Test Checklist (45 items)', 35, 'Sol arka disk — Aynı kontrol. Belirgin şekilde sıcak mı?', NULL, 'adas', 90),
        ('Default Test Checklist (45 items)', 36, 'Sağ arka disk — Aynı kontrol. Belirgin şekilde sıcak mı?', NULL, 'adas', 90),
        ('Default Test Checklist (45 items)', 37, 'N''de aracı ittir — Soğuk teste kıyasla artan direnç var mı? Isınma ile kötüleşiyorsa sıkma kesindir.', NULL, 'infotainment', 100),
        ('Default Test Checklist (45 items)', 38, 'Kapı / Kaput ayarı — Görsel kontrol. Fotoğraf ilet.', NULL, 'infotainment', 100),
        ('Default Test Checklist (45 items)', 39, 'Boya kalitesi — Görsel kontrol. Fotoğraf ilet.', NULL, 'infotainment', 100),
        ('Default Test Checklist (45 items)', 40, 'Trim & Bagaj — İç trim, dış trim düzgün mü? Bagaj yüksekliği doğru mu?', NULL, 'final', 110),
        ('Default Test Checklist (45 items)', 41, 'Tam dönüş kontrolü — Düşük hızda tam sağ/sol manevra. Sürtme, vuruntu veya aks sesi var mı?', NULL, 'final', 110),
        ('Default Test Checklist (45 items)', 42, 'DTC / Diyagnostik tarama — Aktif veya geçmiş hata varsa kayıt altına al. Tarama bitiş saatini not et.', NULL, 'final', 110),
        ('Default Test Checklist (45 items)', 43, 'Mühendis Nihai Onayı', NULL, 'final', 110)
)
INSERT INTO checklist_template_items (
    template_id,
    item_no,
    item_text,
    eol_phase,
    section_key,
    section_sort,
    is_active
)
SELECT
    template.id,
    seed.item_no,
    seed.item_text,
    seed.eol_phase,
    seed.section_key,
    seed.section_sort,
    TRUE
FROM template_items seed
JOIN checklist_templates template
  ON template.name = seed.template_name
 AND template.vehicle_model_id IS NULL
ON CONFLICT (template_id, item_no) DO UPDATE
SET item_text = EXCLUDED.item_text,
    eol_phase = EXCLUDED.eol_phase,
    section_key = EXCLUDED.section_key,
    section_sort = EXCLUDED.section_sort,
    is_active = EXCLUDED.is_active;
