-- Populate the default EOL / Shipment / Test templates created by migration 0002.
WITH template_items (template_name, item_no, item_text, eol_phase) AS (
    VALUES
        -- EOL: 9 BRANCH + 7 DEPOT = 16
        ('Default EoL Template (16 items, Branch + Depot)', 1::SMALLINT, 'Verify exterior paint finish and color consistency', 'BRANCH'::eol_item_phase_enum),
        ('Default EoL Template (16 items, Branch + Depot)', 2, 'Inspect body panel gaps and flushness', 'BRANCH'),
        ('Default EoL Template (16 items, Branch + Depot)', 3, 'Verify door, hood, and liftgate operation', 'BRANCH'),
        ('Default EoL Template (16 items, Branch + Depot)', 4, 'Perform door and window seal leak test', 'BRANCH'),
        ('Default EoL Template (16 items, Branch + Depot)', 5, 'Verify headlamp, tail lamp, and signal operation', 'BRANCH'),
        ('Default EoL Template (16 items, Branch + Depot)', 6, 'Test horn, wipers, washers, and exterior controls', 'BRANCH'),
        ('Default EoL Template (16 items, Branch + Depot)', 7, 'Inspect interior trim, seats, and restraint systems', 'BRANCH'),
        ('Default EoL Template (16 items, Branch + Depot)', 8, 'Run infotainment and instrument cluster function test', 'BRANCH'),
        ('Default EoL Template (16 items, Branch + Depot)', 9, 'Complete diagnostic trouble code scan', 'BRANCH'),
        ('Default EoL Template (16 items, Branch + Depot)', 10, 'Verify charging port and high voltage charging function', 'DEPOT'),
        ('Default EoL Template (16 items, Branch + Depot)', 11, 'Perform warehouse tire pressure and wheel inspection', 'DEPOT'),
        ('Default EoL Template (16 items, Branch + Depot)', 12, 'Perform warehouse fluid and visible leak inspection', 'DEPOT'),
        ('Default EoL Template (16 items, Branch + Depot)', 13, 'Complete warehouse final quality release inspection', 'DEPOT'),
        ('Default EoL Template (16 items, Branch + Depot)', 14, 'Verify accessory pack and tool kit completeness', 'DEPOT'),
        ('Default EoL Template (16 items, Branch + Depot)', 15, 'Confirm depot protective covering and transport readiness', 'DEPOT'),
        ('Default EoL Template (16 items, Branch + Depot)', 16, 'Sign depot release checklist for document phase handoff', 'DEPOT'),

        -- SHIPMENT / Customer Vehicle Checklist: 43 items (unchanged text)
        ('Default Customer Vehicle Checklist (43 items)', 1, 'Verify VIN against production and shipment records', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 2, 'Verify vehicle model, variant, and market specification', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 3, 'Confirm vehicle software release version', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 4, 'Confirm all production checkpoints are recorded', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 5, 'Confirm no critical diagnostic trouble codes are active', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 6, 'Confirm all required campaigns and updates are complete', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 7, 'Inspect front bumper finish and attachment', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 8, 'Inspect rear bumper finish and attachment', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 9, 'Inspect hood surface and alignment', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 10, 'Inspect roof surface and glass', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 11, 'Inspect left body side paint and panels', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 12, 'Inspect right body side paint and panels', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 13, 'Inspect liftgate or trunk finish and alignment', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 14, 'Inspect exterior mirrors and camera lenses', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 15, 'Inspect windshield and window glass', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 16, 'Verify all door seals are seated correctly', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 17, 'Verify driver door lock and release operation', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 18, 'Verify passenger door lock and release operation', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 19, 'Verify rear door lock and release operation', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 20, 'Verify hood and liftgate latch operation', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 21, 'Verify headlamp low and high beam operation', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 22, 'Verify daytime running lamp operation', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 23, 'Verify turn signal and hazard lamp operation', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 24, 'Verify brake and reverse lamp operation', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 25, 'Verify interior and cargo lamp operation', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 26, 'Verify horn, wiper, and washer operation', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 27, 'Verify power window and mirror operation', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 28, 'Verify seat adjustment and heating functions', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 29, 'Verify seat belt condition and warning indicators', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 30, 'Inspect dashboard, console, and interior trim', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 31, 'Verify climate control heating and cooling', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 32, 'Verify infotainment display and audio output', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 33, 'Verify Bluetooth, navigation, and connectivity', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 34, 'Verify instrument cluster indicators and messages', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 35, 'Verify rear view camera and parking sensors', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 36, 'Verify charging cable and accessory equipment', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 37, 'Verify charging port door and connector condition', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 38, 'Verify high voltage battery state of charge', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 39, 'Inspect wheels, tires, and tire pressures', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 40, 'Inspect underbody for damage or fluid leaks', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 41, 'Verify owner documents, labels, and manuals', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 42, 'Remove production protection and clean vehicle', NULL),
        ('Default Customer Vehicle Checklist (43 items)', 43, 'Complete final shipment release approval', NULL),

        -- TEST: 45 end-of-line functional test items
        ('Default Test Checklist (45 items)', 1, 'Static brake pedal travel and firmness check', NULL),
        ('Default Test Checklist (45 items)', 2, 'Dynamic service brake performance test', NULL),
        ('Default Test Checklist (45 items)', 3, 'Parking brake holding force verification', NULL),
        ('Default Test Checklist (45 items)', 4, 'ABS / ESC functional self-test', NULL),
        ('Default Test Checklist (45 items)', 5, 'Wheel alignment camber measurement', NULL),
        ('Default Test Checklist (45 items)', 6, 'Wheel alignment toe measurement', NULL),
        ('Default Test Checklist (45 items)', 7, 'Steering wheel center and free-play check', NULL),
        ('Default Test Checklist (45 items)', 8, 'Headlight aim low-beam pattern verification', NULL),
        ('Default Test Checklist (45 items)', 9, 'Headlight aim high-beam pattern verification', NULL),
        ('Default Test Checklist (45 items)', 10, 'Fog lamp aim and operation check', NULL),
        ('Default Test Checklist (45 items)', 11, 'OBD diagnostic scan for active DTCs', NULL),
        ('Default Test Checklist (45 items)', 12, 'OBD freeze-frame and readiness monitor review', NULL),
        ('Default Test Checklist (45 items)', 13, 'High voltage isolation resistance test', NULL),
        ('Default Test Checklist (45 items)', 14, 'Traction battery state-of-health readout', NULL),
        ('Default Test Checklist (45 items)', 15, 'On-board charger AC charge session test', NULL),
        ('Default Test Checklist (45 items)', 16, 'DC fast-charge handshake smoke test', NULL),
        ('Default Test Checklist (45 items)', 17, 'Drive motor torque / noise roll-bench check', NULL),
        ('Default Test Checklist (45 items)', 18, 'Regenerative braking response verification', NULL),
        ('Default Test Checklist (45 items)', 19, 'Cooling system pressure and flow test', NULL),
        ('Default Test Checklist (45 items)', 20, 'Cabin HVAC temperature pull-down / heat-up test', NULL),
        ('Default Test Checklist (45 items)', 21, 'Battery thermal management loop function test', NULL),
        ('Default Test Checklist (45 items)', 22, 'Tire pressure monitoring system calibration', NULL),
        ('Default Test Checklist (45 items)', 23, 'Speedometer / odometer accuracy check', NULL),
        ('Default Test Checklist (45 items)', 24, 'Road-load / coast-down roll-bench verification', NULL),
        ('Default Test Checklist (45 items)', 25, 'NVH idle and cruise noise assessment', NULL),
        ('Default Test Checklist (45 items)', 26, 'Door close effort and latch durability sample', NULL),
        ('Default Test Checklist (45 items)', 27, 'Power window anti-pinch function test', NULL),
        ('Default Test Checklist (45 items)', 28, 'Keyless entry and passive start authentication', NULL),
        ('Default Test Checklist (45 items)', 29, 'Immobilizer and alarm arm/disarm test', NULL),
        ('Default Test Checklist (45 items)', 30, 'ADAS camera static calibration confirmation', NULL),
        ('Default Test Checklist (45 items)', 31, 'ADAS radar alignment confirmation', NULL),
        ('Default Test Checklist (45 items)', 32, 'Lane-keep assist simulation bench check', NULL),
        ('Default Test Checklist (45 items)', 33, 'Adaptive cruise control simulation bench check', NULL),
        ('Default Test Checklist (45 items)', 34, 'Blind-spot and cross-traffic alert function test', NULL),
        ('Default Test Checklist (45 items)', 35, 'Parking assist sensor coverage test', NULL),
        ('Default Test Checklist (45 items)', 36, 'Surround-view camera image integrity check', NULL),
        ('Default Test Checklist (45 items)', 37, 'Infotainment boot time and touch response check', NULL),
        ('Default Test Checklist (45 items)', 38, 'Bluetooth pairing and hands-free audio test', NULL),
        ('Default Test Checklist (45 items)', 39, 'Emergency call (eCall) module self-test', NULL),
        ('Default Test Checklist (45 items)', 40, 'Exterior lighting sequential function walk', NULL),
        ('Default Test Checklist (45 items)', 41, 'Washer fluid spray pattern and wiper sweep test', NULL),
        ('Default Test Checklist (45 items)', 42, 'Water ingress / spray booth leak check', NULL),
        ('Default Test Checklist (45 items)', 43, 'Underbody fastener torque audit sample', NULL),
        ('Default Test Checklist (45 items)', 44, 'Final road-test driveability sign-off', NULL),
        ('Default Test Checklist (45 items)', 45, 'End-of-line test report archive and stamp', NULL)
)
INSERT INTO checklist_template_items (
    template_id,
    item_no,
    item_text,
    eol_phase,
    is_active
)
SELECT
    template.id,
    seed.item_no,
    seed.item_text,
    seed.eol_phase,
    TRUE
FROM template_items seed
JOIN checklist_templates template
  ON template.name = seed.template_name
 AND template.vehicle_model_id IS NULL
ON CONFLICT (template_id, item_no) DO UPDATE
SET item_text = EXCLUDED.item_text,
    eol_phase = EXCLUDED.eol_phase,
    is_active = EXCLUDED.is_active;
